# Generated by Django 6.0.5 on 2026-05-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gameresult_moves'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanupAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10)),
                ('stale_sessions_detected', models.IntegerField(default=0)),
                ('sessions_removed', models.IntegerField(default=0)),
                ('sessions_resigned', models.IntegerField(default=0)),
                ('duration', models.FloatField(default=0.0, help_text='Duration in seconds')),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
